/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2f3132",
        "secondary-fixed": "#c8c6c8",
        "on-tertiary-fixed-variant": "#e3e2e7",
        "on-secondary-fixed-variant": "#3b3b3d",
        "surface-container-highest": "#e2e2e4",
        "secondary": "#5f5e60",
        "on-surface-variant": "#474747",
        "secondary-container": "#d6d3d6",
        "outline": "#777777",
        "outline-variant": "#c6c6c6",
        "on-tertiary-container": "#ffffff",
        "surface-dim": "#d9dadc",
        "surface-container-high": "#e8e8ea",
        "error": "#ba1a1a",
        "on-primary-fixed": "#ffffff",
        "surface-container-low": "#f3f3f5",
        "on-primary": "#e2e2e2",
        "surface-variant": "#e2e2e4",
        "on-primary-container": "#ffffff",
        "primary-container": "#3b3b3b",
        "tertiary-fixed-dim": "#46464b",
        "surface": "#f9f9fb",
        "surface-tint": "#5e5e5e",
        "tertiary-fixed": "#5e5e63",
        "inverse-on-surface": "#f0f0f2",
        "on-secondary-container": "#1b1b1d",
        "surface-container": "#eeeef0",
        "on-tertiary": "#e3e2e7",
        "on-tertiary-fixed": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#5e5e5e",
        "secondary-fixed-dim": "#acaaad",
        "inverse-primary": "#c6c6c6",
        "primary": "#000000",
        "on-surface": "#1a1c1d",
        "on-primary-fixed-variant": "#e2e2e2",
        "on-error": "#ffffff",
        "background": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary": "#3a3b40",
        "primary-fixed-dim": "#474747",
        "surface-bright": "#f9f9fb",
        "on-error-container": "#410002",
        "tertiary-container": "#747479",
        "on-background": "#1a1c1d",
        "on-secondary-fixed": "#1b1b1d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
}
